title:            SimpleBasics
description:      Technology Information Sharing Worldwide.

# put your disqus here
disqus_shortname: simple-basics
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
#excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://libish-jacob.github.io/Blog

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title : 'About'
    url: '/about'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Archives'
    url: '/archives'
    type: 'archives'
  #- title: 'Contact'
  #  url: '/Contact'
  #  type: 'contact'
  #- title: 'Favorites'
  #  url: '#'
  #  submenu:
  #    - title: 'Code Highlighter'
  #      url: '/intro/code-highlighting-post/'
  #    - title: 'Sample Post'
  #      url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Libish Varghese Jacob
  site:           https://www.linkedin.com/in/libishjacob/
  avatar:         images/libish.jpg
  bio:            "I am currently working as a lead engineer in one of the leading wind turbine manufacturing firm. I have wide range of interests and getting my hands dirty in technology is one among them. I use this platform primarily as my knowledge base. I also use this platform to share my experience and experiments so that it might help someone who is walking the way I already did. The suggestions expressed here are the best to my knowledge at the time of writing and this may not necessarily be the best possible solution. I would pretty much appreciate if you could comment on it to bring into my notice on what could have been done better."
  email:          libi.32@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: libishjacob # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: libish-jacob

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/libish-jacob"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/libishjacob"
  - title: "youtube"
    url: "https://www.youtube.com/"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
#compress_html:
#  clippings: all
#  comments: all
#  endings: all

plugins:
  - jekyll-feed

  #alterable: true

prose:
  rooturl: '_posts'
  siteurl: 'http://localhost:4000/'
  relativeLinks: ''
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"      
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"          
          options:
            - name: "WPF"
              value: "WPF"
            - name: "WCF"
              value: "WCF"
            - name: "C#"
              value: "C#"
            - name: "Log4Net"
              value: "Log4Net"
            - name: "Dos Command"
              value: "Dos Command"
            - name: "Prism"
              value: "Prism"
            - name: "SQLite"
              value: "SQLite"
            - name: "Entity Framework"
              value: "Entity Framework"
            - name: "IIS"
              value: "IIS"
            - name: "Azure"
              value: "Azure"
            - name: "Powershell"
              value: "Powershell"
            - name: "Visual Studio"
              value: "Visual Studio"
            - name: "Apache"
              value: "Apache"
            - name: "Enterprise Library"
              value: "Enterprise Library"
            - name: "Delphi"
              value: "Delphi"

      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Category"
          placeholder: "Choose category"          
          options:
            - name: "Web Server"
              value: "Web Server"
            - name: "Cloud"
              value: "Cloud"
            - name: "Database"
              value: "Database"
            - name: "Operating System"
              value: "Operating System"
            - name: "Network"
              value: "Network"
            - name: "UI Controls"
              value: "UI Controls"
            - name: ".Net"
              value: ".Net"
            - name: "Testing"
              value: "Testing"
            - name: "Source control"
              value: "Source control"
            - name: "IDE"
              value: "IDE"
            - name: "Continuous Integration"
              value: "Continuous Integration"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "description"
        field:
          element: "textarea"
          label: "description"      
      - name: "date"
        field:
          element: "text"
          label: "Date"
      - name: "modified"
        field:
          element: "text"
          label: "Modified date"
          value: "CURRENT_DATETIME"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: true 
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
