title:            GoNetDotNet
description:      Technology Information Sharing Worldwide.

# put your disqus here
disqus_shortname: 
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
#excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://libish-jacob.github.io/DotNet/

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
 # - title: 'Fork'
 #   url: 'http://github.com/aron-bordin/neo-hpstr-jekyll-theme'
 # - title: 'Install'
 #   url: 'http://github.com/aron-bordin/neo-hpstr-jekyll-theme#installation'
  - title : 'About'
    url: '/about'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Archives'
    url: '/archives'
    type: 'archives'
  #- title: 'Contact'
  #  url: '/Contact'
  #  type: 'contact'
  #- title: 'Favorites'
  #  url: '#'
  #  submenu:
  #    - title: 'Code Highlighter'
  #      url: '/intro/code-highlighting-post/'
  #    - title: 'Sample Post'
  #      url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Libish Varghese Jacob
  site:           https://www.linkedin.com/in/libishjacob/
  avatar:         images/libish.jpg
  bio:            "I am currently working as a lead engineer in one of the leading wind turbine manufacturing firm. I have wide range of interests and getting my hands dirty in technology is one among them. I use this platform primarily as my own knowledge base. I share my experiments and experiences to public here so that it might help someone who is walking the way I already did. The suggestions expressed here is the best to my knowledge at the time of writing and this may not necessarily be the best possible solution. I would pretty much appreciate if you could comment on it to bring into my notice what could have been better."
  email:          libi.32@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: libishjacob # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  #github: aron-bordin

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
 # - title: "github"
 #   url: "https://github.com/aron-bordin"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/libishjacob"
  - title: "youtube"
    url: "https://www.youtube.com/"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
#compress_html:
#  clippings: all
#  comments: all
#  endings: all
